### ISSUE TITLE
"Is it up to date?" error 1.19.4

### ISSUE THREAD

**Issue by LordVZlomka** [jaqobb/message-editor#39]
I'm running a 1.19.4 version with the latest protocol lib, and it causes this error
![image](https://user-images.githubusercontent.com/71541816/235818761-a0ed4d93-184d-4eb2-8bd0-abd3eb6068a1.png)
![image](https://user-images.githubusercontent.com/71541816/235818812-36d960e0-6f3b-4dd8-abf3-a362ec684b7b.png)

**Comment by jaqobb** [comment]
The newest version of ProtocolLib had a change in some parts of the API and Message Editor 2.5.1 is still using the old API. In order to fix the startup issue, either downgrade ProtocolLib or use the snapshot version of Message Editor that uses the new API.

You can download said Message Editor version here: https://github.com/jaqobb/message-editor/suites/12425096779/artifacts/661114838

**Comment by jaqobb** [comment]
Message Editor 2.5.2 has been released, fixing Paper issue and bumping ProtocolLib API among other things.
